const HomeIcon = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-5" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z" /><path strokeLinecap="round" d="M9 21v-7h6v7" /></svg>
const ProfileIcon = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-5" aria-hidden="true"><circle cx="12" cy="8" r="4" /><path strokeLinecap="round" d="M4 21a8 8 0 0 1 16 0" /></svg>
const DutyIcon = () => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-5" aria-hidden="true"><rect x="4" y="6" width="16" height="15" rx="2" /><path strokeLinecap="round" d="M8 3v6m8-6v6M4 11h16m-12 5h8" /></svg>

export default function EmployeeSidebar({ section, onSectionChange, user, onExit }) {
  const items = [{ id: 'overview', label: 'Overview', icon: HomeIcon }, { id: 'duties', label: 'My duties', icon: DutyIcon }, { id: 'profile', label: 'My profile', icon: ProfileIcon }]
  return <aside className="hidden min-h-screen w-64 shrink-0 border-r border-rose-100 bg-white px-5 py-7 lg:flex lg:flex-col">
    <div className="flex items-center gap-3 px-2"><span className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-rose-600 to-pink-500 text-lg font-bold text-white shadow-md shadow-rose-200">S</span><div><p className="text-lg font-bold tracking-tight text-slate-900">Servnix</p><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-rose-500">Employee space</p></div></div>
    <p className="mt-12 px-3 text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Workspace</p>
    <nav className="mt-3 space-y-1" aria-label="Employee navigation">{items.map(({ id, label, icon: Icon }) => <button className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${section === id ? 'bg-rose-50 text-rose-700 ring-1 ring-rose-100' : 'text-slate-600 hover:bg-stone-50 hover:text-slate-900'}`} type="button" key={id} aria-current={section === id ? 'page' : undefined} onClick={() => onSectionChange(id)}><Icon />{label}</button>)}</nav>
    <div className="mt-auto border-t border-stone-100 pt-5"><div className="flex items-center gap-3 rounded-xl bg-stone-50 p-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-rose-100 text-sm font-bold text-rose-700">{user.name?.charAt(0)?.toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{user.name}</p><p className="truncate text-xs text-slate-500">Employee account</p></div></div><button className="mt-3 w-full rounded-xl px-4 py-2.5 text-left text-sm font-semibold text-slate-500 transition hover:bg-rose-50 hover:text-rose-700" type="button" onClick={onExit}>Log out</button></div>
  </aside>
}
