import EmployeeProfile from '../../components/dashboard/employee/EmployeeProfile.jsx'
import EmployeeShell from '../../components/dashboard/employee/common/EmployeeShell.jsx'
import { useGetEmployeeProfileQuery } from '../../redux/Api/employee/EmployeeApi.js'
import EmployeeInvitations from '../../components/dashboard/employee/EmployeeInvitations.jsx'
import EmployeeDuties from '../../components/dashboard/employee/EmployeeDuties.jsx'

function EmployeeOverview({ user, onProfile }) {
  const { data, isLoading, error } = useGetEmployeeProfileQuery()
  const complete = data?.isComplete
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#64233f] via-[#a92660] to-[#e85882] p-8 text-white shadow-xl shadow-rose-200/60 sm:p-10"><div className="absolute -right-14 -top-16 size-56 rounded-full border border-white/20 bg-white/5" aria-hidden="true" /><div className="absolute -bottom-28 right-24 size-64 rounded-full border border-white/15" aria-hidden="true" /><div className="relative"><p className="text-xs font-bold uppercase tracking-[0.2em] text-rose-100">Your workspace</p><h1 className="mt-4 max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Good to see you, {user.name?.split(' ')[0]}.</h1><p className="mt-3 max-w-xl text-sm leading-7 text-rose-50">A clear place to keep your professional information ready and up to date.</p><button className="mt-7 rounded-xl bg-white px-5 py-3 text-sm font-bold text-rose-700 shadow-sm transition hover:bg-rose-50" type="button" onClick={onProfile}>{complete ? 'View my profile' : 'Complete my profile'}</button></div></section>
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]"><section className="rounded-3xl border border-stone-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-rose-600">Getting started</p><h2 className="mt-3 text-xl font-semibold text-slate-900">Your professional profile</h2><p className="mt-2 text-sm leading-6 text-slate-600">Add your contact details, location, and job title. You can update them whenever they change.</p><div className="mt-6 flex items-center gap-4 rounded-2xl bg-stone-50 p-4"><span className={`grid size-11 shrink-0 place-items-center rounded-xl text-lg font-bold ${complete ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{complete ? '✓' : '1'}</span><div><p className="text-sm font-semibold text-slate-900">{isLoading ? 'Checking profile...' : error ? 'Profile unavailable' : complete ? 'Profile completed' : 'Profile details needed'}</p><p className="mt-1 text-xs text-slate-500">{complete ? 'Your information is saved.' : 'Open My profile to finish setup.'}</p></div></div></section><section className="rounded-3xl border border-rose-100 bg-rose-50/70 p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-rose-600">Account</p><div className="mt-5 grid size-14 place-items-center rounded-2xl bg-white text-xl font-bold text-rose-700 shadow-sm">{user.name?.charAt(0)?.toUpperCase()}</div><h2 className="mt-4 text-xl font-semibold text-slate-900">{user.name}</h2><p className="mt-1 break-all text-sm text-slate-600">{user.email}</p><p className="mt-4 inline-flex rounded-full bg-white px-3 py-1 text-xs font-semibold text-rose-700">Employee</p>{data?.profile?.organizationName && <p className="mt-4 border-t border-rose-100 pt-4 text-sm font-medium text-slate-700">Organization: {data.profile.organizationName}</p>}</section></div>
    <EmployeeInvitations />
  </div>
}

export default function EmployeeDashboardPage({ user, section, onSectionChange, onExit, onUserUpdate }) {
  return <EmployeeShell user={user} section={section} onSectionChange={onSectionChange} onExit={onExit}>{section === 'profile' ? <EmployeeProfile user={user} onUserUpdate={onUserUpdate} /> : section === 'duties' ? <EmployeeDuties /> : <EmployeeOverview user={user} onProfile={() => onSectionChange('profile')} />}</EmployeeShell>
}
